GET http://localhost:4000/api/v1/inspections

###

DELETE  http://localhost:4000/api/v1/inspections/5e721d7b94f4c9471f2991b8


###

GET http://localhost:4000/api/v1/inspections/5e721d7b94f4c9471f2991b8

###

GET http://localhost:4000/api/v1/inspections/facility/5e6d380d16ad027734cee0c7

###

POST  http://localhost:4000/api/v1/inspections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncm91cHMiOlsiQWRtaW5pc3RyYXRvciIsIlVzZXIiXSwiX2lkIjoiNWU2ZjQyMzZhNjEyMGY1MWNkNWEyZTY0IiwibmFtZSI6IkVkZ2FyIEVuZG8iLCJ1c2VybmFtZSI6ImVuZG9lZGdhciIsImVtYWlsIjoiZW5kb2VkZ2FyanVuaW9yQGdtYWlsLmNvbSIsIl9fdiI6MCwiYmlvIjoiVGhpcyBpcyBhIGJpby4gSSBjYW4gdHlwZSB3aGF0ZXZlciBJIHdhbnQgaGVyZS4iLCJpYXQiOjE1ODQ1MDU5OTZ9.hM4jUOrTPgmbrUZqDisFavd6bLT1G6l6vIUSOrIo1es

{
    "facility": "5e70d7e97c820a4dcb354058",
    "type": "Health",
    "report": "Peter has Corona", 
    "rating": "0.5"
}

###

PATCH http://localhost:4000/api/v1/inspections/5e6d6a368a489e21525699b0
Content-Type: application/json

{
    "report": "Sink is broken and Chairs are broken",
    "rating": "1.5"
}

