GET http://localhost:4000/api/v1/inspections

###

DELETE  http://localhost:4000/api/v1/inspections/5e721d7b94f4c9471f2991b8


###

GET http://localhost:4000/api/v1/inspections/5e721d7b94f4c9471f2991b8

###

GET http://localhost:4000/api/v1/inspections/facility/5e6d380d16ad027734cee0c7

###

POST  http://localhost:4000/api/v1/inspections
Content-Type: application/json

{
    "facility_id": "5e6ac55b61295e04f44774c3",
    "inspector_id": "5e6f9ed7577f735bcf0e5b88",
    "type": "Health",
    "report": "Peter has Corona", 
    "rating": "0.5"
}

###

PATCH http://localhost:4000/api/v1/inspections/5e6d6a368a489e21525699b0
Content-Type: application/json

{
    "report": "Sink is broken and Chairs are broken",
    "rating": "1.5"
}

